사망아이템드롭:
  최소: 3
  최대: 7
기본금: 100000
킬골드: 10000
사망골드: -10000
월드지름: 5000
시작레벨: 10
스테미나:
  기본: 10000
  달리기: -15
  수영: -30
  점프: -150
  공격: -700
  데미지: -300
  채광: -700
  설치: -150
  초당회복: 200
  웅크리기: 300
  마시기: 1500
  먹기:
    HONEY_BOTTLE: 7000
    MILK_BUCKET: 3000
    SWEET_BERRIES: 200
    GLOW_BERRIES: 200
  디버프1: 2500
  디버프2: 500
  버프: 9000
  엑션바:
    가중치: 50
    이름: '스테미나'
    메세지: '&f{amount}'
    지속시간: 3
    일회성: true
    길이: 75
offset:
  point:  #월드에딧 카피할때 기준점 때문에 생긴 offset
    x: -1
    y: 1
    z: -1
  center:   #실제 설치할 때 중심 맞추기 위한 offset
    x: -4
    y: -1
    z: -4
구조물:
  spawn:
    name: 'spawn'
    count: 0
    world: 'Civilization'
    variants:
      - ''
    offset:
      center:
        x: 0
        y: -1
        z: 0
  crack:
    name: 'crack'
    count: 1
    world: 'Civilization'
    loots: 'crack'
    variants:
      - '1'
  ruin:
    name: 'ruin'
    count: 10
    world: 'Civilization'
    loots: 'ruin'
    variants:
      - '1'
      - '2'
  altar:
    name: 'altar'
    count: 5
    world: 'Civilization'
    variants:
      - '1'
  lode:
    name: 'lode'
    count: 10
    world: 'Civilization'
    loots: 'lode'
    variants:
      - '1'
  portal1:
    name: 'portal'
    count: 2
    world: 'Civilization'
    variants:
      - '1'
  portal2:
    name: 'portal'
    count: 2
    world: 'Civilization'
    variants:
      - '2'
  temple:
    name: 'temple'
    count: 5
    world: 'Civilization_Nether'
    variants:
      - '1'
초반무적:
  분: 5
  초: 0
리스폰무적:
  분: 0
  초: 15
현상금:
  범위: 3
  -3: -10000
  -2: -5000
  -1: -1000
  0: 0
  1: 3000
  2: 7000
  3: 15000
돈:
  코드: 'PAPER'
  속성숨기기: true
  반짝임: true
  이름: '{amount}원'
  로어:
    - '&7{amount}원'
    - '&8위조 방지용 문구'
기본템:
  '1':
    코드: 'OAK_PLANKS'
    개수: 64
  '2':
    코드: 'BREAD'
    개수: 16
  '3':
    코드: 'HONEY_BOTTLE'
    개수: 3
  '4':
    코드: 'OAK_BOAT'
  '5':
    코드: 'TORCH'
    개수: 32
승리:
  타이틀1:
    이름: '승리'
    가중치: -999
    타이틀: '&fCongratulation!'
    서브타이틀: '&6Winner: &7{winner}'
    페이드인: 1
    지속시간: 10
    페이드아웃: 1
  메세지1:
    이름: '승리'
    가중치: -999
    메세지: '&fThe Winner is &6{winner}&f!'