사망아이템드롭:
  최소: 3
  최대: 7
기본금: 100000
킬골드: 10000
사망골드: -10000
월드지름: 5000
초반무적:
  시간: 1
  분: 0
  초: 0
현상금:
  범위: 3
  -3: -10000
  -2: -5000
  -1: -1000
  0: 0
  1: 3000
  2: 7000
  3: 15000
돈:
  코드: 'PAPER'
  속성숨기기: true
  반짝임: true
  이름: '{amount}원'
  로어:
    - '&7{amount}원'
    - '&8위조 방지용 문구'